import { Game, GameCategory } from "./types";

export const GAMES_DB: Game[] = [
  {
    id: "ball-sort-puzzle",
    name: "Ball Sort Puzzle",
    description: "Sort colorful compound balls in chemistry bottles until each bottle contains only one color.",
    category: GameCategory.PUZZLE,
    playTime: "2 min",
    difficulty: "Medium",
    players: "Solo",
    tags: ["Logic", "Sorting", "Colors", "Classic"],
    mobileFriendly: true,
    isPopular: true,
    isNew: true,
    icon: "FlaskConical",
    howToPlay: "Tap a tube to select its top-most ball. Tap another tube to pour the ball. You can only place a ball on top of another ball of the exact same color, or into an empty tube. Group all colors to solve!",
    whyYouWillLikeIt: "Highly relaxing, beautiful visual aesthetics, and extremely satisfying when you successfully clean and group every color chemistry tube."
  },
  {
    id: "pattern-panic",
    name: "Pattern Panic",
    description: "Spot the hidden odd shape or color aberration before the shrinking timer runs out.",
    category: GameCategory.PUZZLE,
    playTime: "30s",
    difficulty: "Medium",
    players: "Solo",
    tags: ["Visual", "Reflex", "Speed", "Colors"],
    mobileFriendly: true,
    isPopular: true,
    isNew: true,
    icon: "Grid",
    howToPlay: "A grid of custom shapes will appear. One block is slightly different in color, rotation, or scale. Tap the odd block as fast as possible to gain time and advance to next level. Don't make wrong taps or you'll lose valuable seconds!",
    whyYouWillLikeIt: "Fast-paced, satisfying sound cues, and escalating grid complexity (up to 7x7) that perfectly tests and sharpens your peripheral vision."
  },
  {
    id: "odd-one-out",
    name: "Odd One Out",
    description: "Who doesn't fit the group? A local pass-and-play party game of associations.",
    category: GameCategory.PARTY,
    playTime: "2 min",
    difficulty: "Easy",
    players: "1-4 Players",
    tags: ["Party", "Words", "Local Play", "Humorous"],
    mobileFriendly: true,
    isPopular: false,
    isNew: true,
    icon: "Users",
    howToPlay: "Four words or emojis are presented. One is logically or contextually different. Can you find it? Supports Solo practice or Local Multiplayer mode where up to 4 friends take turns and compete for the highest speed and score!",
    whyYouWillLikeIt: "Hilarious category combinations and direct competition make it the perfect icebreaker game when you're hanging out with friends."
  },
  {
    id: "tiny-oracle",
    name: "Tiny Oracle",
    description: "Ask the Cosmic Oracle anything and receive magical, witty, or sarcastic predictions.",
    category: GameCategory.PARTY,
    playTime: "1 min",
    difficulty: "Easy",
    players: "Solo",
    tags: ["AI", "Mystic", "Humorous", "Magic"],
    mobileFriendly: true,
    isPopular: true,
    isNew: false,
    icon: "Sparkles",
    howToPlay: "Enter a burning question about your life, career, or code. Tap the magical orb to channel cosmic energy. The Oracle will generate a custom, funny prediction, assign a cosmic Vibe Score, and give you a lucky emoji symbol!",
    whyYouWillLikeIt: "Powered by Gemini, its answers are uniquely generated, witty, and wonderfully cosmic, giving you a quick smile anytime of day."
  },
  {
    id: "reaction-speed",
    name: "Neon Aim Trainer",
    description: "Test your reaction speed and hand-eye coordination by tapping active neon nodes.",
    category: GameCategory.REACTION,
    playTime: "30s",
    difficulty: "Hard",
    players: "Solo",
    tags: ["Reflex", "Neon", "Clicker", "Arcade"],
    mobileFriendly: true,
    isPopular: false,
    isNew: true,
    icon: "Zap",
    howToPlay: "Neon circular target nodes will rapidly expand and shrink in the dark playground. Click or tap them as fast as possible before they disappear. Missing a node or letting it decay will end your streak. Rack up points in 30 seconds!",
    whyYouWillLikeIt: "A highly responsive arcade playground featuring custom particle splash effects, neon glow visual styling, and instant high-score logging."
  }
];
